apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::017387260479:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::017387260479:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1POSQ6CMU0LGM
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-08-01T01:36:51Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "825"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: d28c6e2f-56fd-4b44-821f-f0584444b0c0
